### ISSUE TITLE
Bug: `vim.go.filetype` is set to `fzf` after using an fzf-lua picker

### ISSUE THREAD

**Issue by garlicbreadcleric** [ibhagwan/fzf-lua#1609]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [ ] I have read the Wiki including the Advanced section
- [ ] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Linux

### Shell

fish

### Neovim version (`nvim --version`)

v0.10.2

### Fzf version (`fzf --version`)

0.57.0 (installed via adding junegunn/fzf as a lazy.nvim plugin)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--color light

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
{
  'junegunn/fzf',
  cond = is_vanilla,
},
{
  "ibhagwan/fzf-lua",
  cond = is_vanilla,
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("fzf-lua").setup({ 'borderless_full', fzf_colors = true })
  end,
},
```

### Describe the bug / steps to reproduce

I'm not 100% sure if this is an issue at all or if this is expected, but I've noticed it while trying to debug a weird filetype-related issue.

1. Open Neovim
2. `:setglobal filetype` doesn't return anything
3. Open `:FzfLua files`, then close it
4. `:setglobal filetype` now returns `fzf`

---

For context, in case it turns out to be relevant, the original issue I tried to figure out was that sometimes `commentstring` in my TypeScript files gets randomly changed to `# %s` (as a global option, i.e. `:setglobal commentstring`). After looking into it, it turned out that it was set by `.../nvim/runtime/syntax/dockerfile.vim`. However, I haven't opened any Docker files and don't have any Docker-related Neovim onfiguration/plugins, and the only place Docker files show up is in fzf-lua previews before I type enough to narrow down search to the files I actually want to open. So that plus this weird global `filetype=fzf` thing makes me think it might be an issue with fzf-lua previewer setting some options globally when it shouldn't.

**edit**: I was able to reproduce `setglobal commentstring` being `# %s` on `mini.sh` as well. It's not very predictable though, I had to switch back and forth between fzf-lua results including dockerfiles a bit before it occurred (with my setup it doesn't always happen predictably as well).

**Comment by ibhagwan** [comment]
>  I was able to reproduce setglobal commentstring being # %s on mini.sh as well. It's not very predictable though, I had to switch back and forth between fzf-lua results including dockerfiles a bit before it occurred (with my setup it doesn't always happen predictably as well).

Can you help me hone in on the issue:
- Which file's filetype gets messed up? the origin file (where fzf-lua was called from) or some other random file in the preview?
- Do you feel this happens due to the preview? If so can you try with `previewer=bat` which is an external process and doesn't have to set `ft` for anything?

**Comment by garlicbreadcleric** [comment]
@ibhagwan appreciate a quick response!

- It's the origin file. Essentially after calling fzf-lua I start getting wrong comment syntax while using `mini.comment`
- With `previewer=bat` on `mini.sh` it still sets `setglobal filetype=fzf`, but doesn't seem to be affecting `setglobal commentstring` so far.

**Comment by ibhagwan** [comment]
> it still sets `setglobal filetype=fzf`

This is so funny, this line has been there since pretty much the first line of fzf-lua and I never realized it wasn't local to the buffer.

Can you update to https://github.com/ibhagwan/fzf-lua/commit/a6761dd7e8a95b2b406809fad273faaa442e7340 and see if that helps (IMHO the change was required regardless of this issue).

**Comment by garlicbreadcleric** [comment]
Tried with this commit. The `filetype` doesn't change now; the `commentstring` still does but it doesn't seem to affect `mini.comment` now, at least so far :sweat_smile:

**Comment by ibhagwan** [comment]
> Tried with this commit. The filetype doesn't change now; the commentstring still does (with default previewer) but it doesn't seem to affect mini.comment now, at least so far 😅

Thats great!

> edit: the funny thing is also that previewing any other file types doesn't affect commentstring, it only happens with Dockerfiles.

Perhaps something with your config (although you said you tested mini.sh...) or an ftplugin runtime issue? Wouldn't be far fetched, recently had a serious mystery solved in #1555.

**Comment by garlicbreadcleric** [comment]
Well if it seems that at this it's not on fzf-lua side, I'll close it. Thanks for helping with this, tbh still not 100% sure if fzf-lua played a part in this or it's unrelated and will just reappear again after a while lol, but at least some little thing got fixed :)

**Comment by ibhagwan** [comment]
> Well if it seems that at this it's not on fzf-lua side, I'll close it. Thanks for helping with this, tbh still not 100% sure if fzf-lua played a part in this or it's unrelated and will just reappear again after a while lol, but at least some little thing got fixed :)

If you need my help don't hesitate to reopen, cheers :-)
