### ISSUE TITLE
Code Action not working when opening other file

### ISSUE THREAD

**Issue by abenz1267** [ibhagwan/fzf-lua#319]
Hi again,

i just noticed that code action(s ?) break, when opening a different file. Example:

File 1 > Organize Imports > works.
Open File 2 via fzf-lua > Organize Imports > doesn't do anything.

Works fine with native vim.ui.select.

Regards

**Comment by ibhagwan** [comment]
Can't seem to reproduce it, just tested with both `lua-language-server` and `gopls`, did you override any of the LSP paramters in your config so I can try to match it?

**Comment by abenz1267** [comment]
I made a screen recording: https://drive.google.com/file/d/147kHAa30BuQABqMYvrGlBy_ba6soCJbY/view?usp=sharing

I've also tested with gopls and you are right: no problem there.

Using the native vim.ui.select widget though, it works with jdtls as well. Not sure if this info helps you in any way....

Regards

**Comment by ibhagwan** [comment]
>I made a screen recording: https://drive.google.com/file/d/147kHAa30BuQABqMYvrGlBy_ba6soCJbY/view?usp=sharing

I see, there's not even a notice that says "no actions found", not really sure what is happening here, this might be a `jdtls` isolated issue (may or may not be solveable inside fzf-lua).

If you wish to dig further into this we can try and dump the code actions here and maybe write a few lines of code and try to run `vim.lsp.util.apply_workspace_edit` directly bypassing fzf-lua and seeing if consecutive calls to the neovim API directly yield any results.

If you're happy with the `vim.ui.select` solution and don't really care I also don't mind closing this issue as long as it's isolated to `nvim-jdtls`.

**Comment by ibhagwan** [comment]
Forgot to mention, plugin must be updated to the latest commit for the above to work https://github.com/ibhagwan/fzf-lua/commit/f504b9b09aa96e9b04af9981e9780138e011905f

**Comment by abenz1267** [comment]
The action doesn't even work with nvim-jdtls. works with gopls.

**Comment by ibhagwan** [comment]
> The action doesn't even work with nvim-jdtls. works with gopls.
> 
> Like: i can run the CA with `<CR>`, but not with `<ctrl-y>`. Can do both with gopls.

But do you get any output at all in `:messages`?

**Comment by abenz1267** [comment]
Nope. Nothing.

**Comment by ibhagwan** [comment]
>Nope. Nothing. As if i didn't even press <ctrl-y>. The windows doesn't close, nothing. just nothing happens.

And the same works with `gopls`? Maybe you have a conflicting bind? can you trying changing `ctrl-y` to `ctrl-x` or anything else that isn't in use?

Do you see the `ctrl-y` in the mapping (as `function:0x...`) if you press `F1` while in the code action selection?

![image](https://user-images.githubusercontent.com/59988195/150417017-a5805db9-3e49-494c-ba35-72076020a9f2.png)

**Comment by abenz1267** [comment]
Haha, i know how weird this sounds. I already rebound it to alt-y as well just to try out. 

Just tested: i don't see it when pressing F1. I see it with gopls though.

**Comment by abenz1267** [comment]
Keep in mind nvim-jdtls isn't using nvim-lspconfig!!! Maybe that's related.

**Comment by ibhagwan** [comment]
> Haha, i know how weird this sounds. I already rebound it to alt-y as well just to try out.
> Just tested: i don't see it when pressing F1. I see it with gopls though.

This is some wild stuff lol, how would `nvim-jdtls` actions affect fzf-lua variables... I'm confused :-)

I'm suspecting you don't see it because you're actually seeing the `vim.ui.select` screen, is it possible your mapping for `nvim-jdtls` is actually running `vim.lsp.buf.code_action()` instead?

**Comment by abenz1267** [comment]
ofc it is, as code actions otherwise don't work, as we've established some days ago. that was the reason for you implementing vim.ui.select to begin with

**Comment by ibhagwan** [comment]
> ofc it is, as code actions otherwise don't work, as we've established some days ago. that was the reason for you implementing vim.ui.select to begin with

You need to run the actual `lsp_code_actions` for `ctrl-y` to be mapped, it's not going to happen with `vim.ui.select`, can you try with `:FzfLua lsp_code_actions` - you should have the `ctrl-y` there.

**Comment by abenz1267** [comment]
Yes, but then we are at the `No delegateCommandHandler for java.action.organizeImports ` issue so it won't work anyways. You HAVE to use vim.lsp.buf.code_actions() and therefore vim.ui.select.

**Comment by ibhagwan** [comment]
Oh I see, so this is totally unrelated to the code I sent you... I guess I misunderstood the issue...

So you're still using `vim.ui.select` but if you're using `fzf-lua`'s interface the code action fails and if you're using the native interface it works?

**Comment by abenz1267** [comment]
It breaks with FzfLua as soon as i switch to a different file, BUT it does work for the first file if i switch back to it. So:

File 1 > organize imports > works.
File 2 > organise imports > doesn't do anything
Back to File 1 > organize imports > works.

**Comment by ibhagwan** [comment]
Got it! my bad, reproduced this easily now, will have a fix soon I hope, pretty sure the issue is with `fzf-lua`.

**Comment by abenz1267** [comment]
Haha, good to hear man. Sorry if i wasn't clear enough about the issue.

**Comment by ibhagwan** [comment]
Should work now sorry for the confusion :-)

**Comment by abenz1267** [comment]
No, still doesn't work. Double checked i've updated FzfLua.... latest commit. Not working :-P

**Comment by ibhagwan** [comment]
Can you **updated again to the latest commit** and add the below to you `register_ui_select` and let me know if you see any dump in `:messages` when pressing `<CR>`?

```lua
require'fzf-lua'.register_ui_select({
  actions = {
      ["default"] = function(selected, o)
        print("selected:", selected[1])
        local idx = selected and tonumber(selected[1]:match("^(%d+).")) or nil
        _G.dump(idx, o._items[idx])
        o._on_choice(idx and o._items[idx] or nil, idx)
      end
  }
})
```

**Comment by abenz1267** [comment]
Just wanted to do so and noticed it works? Did you change anything else? Maybe my nvim had some caching issue or whatever when updating before? I don't know.

**Comment by ibhagwan** [comment]
> Just wanted to do so and noticed it works? Did you change anything else? Maybe my nvim had some caching issue or whatever when updating before? I don't know.

Didn't change anything other than allowing this debug code to work, is it possible your nvim didn't update properly?

You can check the commit by going into the `fzf-lua` folder (mine is `~/.local/share/nvim/site/pack/packer/start/fzf-lua`) and running `git rev-parse HEAD`

**Comment by ibhagwan** [comment]
Gotcha, ty for helping tackle this :-)

**Comment by ibhagwan** [comment]
FYI, latest commit https://github.com/ibhagwan/fzf-lua/commit/59fdcdc3e0e9a6603242be4abfac1d4fd755d7eb makes it so registering for `vim.ui.select` is not required for code actions.

The new behavior detects if neovim version > 0.6 and if so it will register autimatically for the code action and then deregister after selection (or cancellation).
