### ISSUE TITLE
null buffer created on "go to definition"

### ISSUE THREAD

**Issue by ldelossa** [ibhagwan/fzf-lua#341]
Hello,

When I use "go to definition" a null buffer seems to be created. Screen cap provided. 

https://user-images.githubusercontent.com/5642902/153277123-bdeea6a5-edfc-4f4e-b3ab-41b8eb54b38b.mp4

**Comment by ibhagwan** [comment]
Does this happens consistently or only with certain definitions / languages?
Does this also happens in other LSP commands (refs, diag, symbols) or just with definitions?

Can you try and see if this happen with:
- `:lua vim.lsp.buf.definition()`
- `:lua require'fzf-lua'.lsp_definitions({ force_uri = false })`

`force_uri` is a new setting (added in #336) that (by default) uses `vim.lsp.util.jump_to_location` instead of a noral file edit in order to add the location to the `tagstack` as naturally happens with `:lua vim.lsp.buf.definition()`

**Comment by ldelossa** [comment]
It doesn't happen with both 
```
:lua vim.lsp.buf.definition()
:lua require'fzf-lua'.lsp_definitions({ force_uri = false })
```

**Comment by ibhagwan** [comment]
I'm trying to reproduce it, what about these?
>Does this happens consistently or only with certain definitions / languages?
>Does this also happens in other LSP commands (refs, diag, symbols) or just with definitions?

**Comment by ldelossa** [comment]
I just tried same thing with lua LSP. I get another blank buffer, but it says "[No Name]:1" this time.

**Comment by ibhagwan** [comment]
Should work now, let me know?

**Comment by ldelossa** [comment]
Fixed :) Thank you.

**Comment by nyngwang** [comment]
This happened to me too.

**Comment by chunleng** [comment]
@ibhagwan Not sure if I got the above right?
After the patch it seems that I still need `{ force_uri = false }` for it to work.
The following still shows the same problem for me

- :lua require'fzf-lua'.lsp_definitions()
- :FzfLua lsp_definitions

Thank you so much for maintaining this plugin, it's my first day switching over from fzf.vim and loving it so much!

**Comment by ibhagwan** [comment]
@chunleng, this seems to be a slightly different issue, the original issue was the creation of a `[No Name]` buffer but the navigation to the selected item succeeded, here it's failing for some reason, can you try the below code and see **(a)** does it work and **(b)** How does the output look in `:messages` when selecting an item?

> You can exec the below with `:lua _G.lsp_definitions()`
```lua
_G.lsp_definitions = function(opts)
  opts = opts or {}
  opts.actions = {
    ['default'] = function(selected, o)
      local entry = require'fzf-lua.path'.entry_to_file(selected[1], o.cwd, true)
      _G.dump(entry)
      vim.lsp.util.jump_to_location(entry, "utf-16")
    end
  }
  require'fzf-lua'.lsp_definitions(opts)
end
```

**Comment by chunleng** [comment]
I got the following...
```
{
  col = 28,
  line = 411,
  range = {
    start = {
      character = 27,
      line = 410
    }
  },
  stripped = "file://vimrc_files/init.lua:411:28:                         _G.lsp_definitions = function(opts)",
  uri = "file://vimrc_files/init.lua"
}
```

Anyway, I think I forgot to mention that it works totally fine if the path is out of the project folder. So I guess there's some problem resolving to cwd path?

**Comment by chunleng** [comment]
Anyway, when it is out of project folder, this is what's being shown.

```
{
  col = 10,
  line = 10,
  range = {
    start = {
      character = 9,
      line = 9
    }
  },
  stripped = "file:///Users/chunlenglim/.local/share/nvim/lsp_servers/sumneko_lua/extension/server/meta/LuaJIT en-us utf8/package.lua:10:10: function require(modname) end",
  uri = "file:///Users/chunlenglim/.local/share/nvim/lsp_servers/sumneko_lua/extension/server/meta/LuaJIT en-us utf8/package.lua"
}
```

The uri resolution seems like the cause of this problem

**Comment by chunleng** [comment]
The issue is gone! Thank you for the quick response!
