### ISSUE TITLE
`cwd` property doesn't affect `files` listing

### ISSUE THREAD

**Issue by megalithic** [ibhagwan/fzf-lua#43]
First off, I _love_ this plugin! Tthank you @ibhagwan and @vijaymarupudi !!

Small issue I've been having... when passing in a specific `cwd` property (`:lua require("fzf-lua").files({ cwd = ~/.config })`), the file listing does not load those files, but instead the files from my actual current working directory that i started the file in, essentially the same as `cwd=''`. Though, the preview window tries to load a preview of those files, but the preview window seems to be "in" the passed in cwd. 

Any thoughts? Are there other things that must happen to have the given `cwd` take affect for the files listing?

**Comment by ibhagwan** [comment]
Stupid question but did you try to add quotes? I.e. `cwd = “~/.config”`?

You can see how I use `cwd` for the same functionality you’re after [here](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugin/fzf-lua/init.lua#L250)

**Comment by megalithic** [comment]
Not a stupid question at all! I wish it were something obvious, yes I have and more. 

Here’s a more exact representation of what I’ve tried:
https://github.com/megalithic/dotfiles/blob/b4733b76300551e1c880573f48c91c5ad52471eb/nvim/.config/nvim/lua/mappings.lua#L182

**Comment by ibhagwan** [comment]
> Not a stupid question at all! I wish it were something obvious, yes I have and more.
> 
> Here’s a more exact representation of what I’ve tried:
> https://github.com/megalithic/dotfiles/blob/b4733b76300551e1c880573f48c91c5ad52471eb/nvim/.config/nvim/lua/mappings.lua#L182

Alright found the problem, you do not have `fd` installed so the command falls back to `find` which has a bug with a specified path, I'm on it, will have a fix soon.

**Comment by ibhagwan** [comment]
Update your plugin and it should work now.

Feel free to close the issue if the answer is yes.

**Comment by megalithic** [comment]
Apologies for delay in responding. I'm still having the same issue and `fd` is being used (not sure where you saw `find` actively being used). Here are my settings for `files` just in case: https://github.com/megalithic/dotfiles/blob/main/nvim/.config/nvim/lua/settings.lua#L717-L728

Thanks again for checking this out. Do I need to alter my `files` default cmd in any way?

**Comment by megalithic** [comment]
I'll get a screencast showing hte behaviour too

**Comment by ibhagwan** [comment]
> Apologies for delay in responding. I'm still having the same issue and `fd` is being used (not sure where you saw `find` actively being used).

I concluded you were using find as I found a bug where find was being used with the `cwd` property.

>Here are my settings for `files` just in case: https://github.com/megalithic/dotfiles/blob/main/nvim/.config/nvim/lua/settings.lua#L717-L728
> 
> Thanks again for checking this out. Do I need to alter my `files` default cmd in any way?

Yes, this is your issue here, if you look at [files#L13](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/files.lua#L13) you’ll see that once you set `cmd` all other parameters are ignored, in order to achieve what you want change `cmd` to `fd_opts` and remove `fd` from the variable (so only the command line args are sent).

Let me know if that solves your issue?

Also, can you share details about your comment regarding the failing of `git_icons = true` so I can fix it?

**Comment by megalithic** [comment]
BRILLIANT! Thank you so very much @ibhagwan !! - closing

Also, I believe the git issue I was seeing with using `git_icons` set to true is now resolved, too. 🙏
Thanks for everything!

**Comment by ibhagwan** [comment]
Great! 

The real issue here is due to me adding new functionality and still not having the time to write proper documentation, `cmd` having absolute control over `files` is not intuitive nor self explanatory.
