### ISSUE TITLE
How can I exclude folders for lsp_live_workspace_symbols?

### ISSUE THREAD

**Issue by ajitid** [ibhagwan/fzf-lua#468]
I can understand that I'd need to to pass params to fd and rg for `files` and `grep` commands respectively but I'm unsure what would work for `lsp_live_workspace_symbols`. nvim-telescope is able to respect ignore paths, so I know it's possible, but I don't know how it can be used in fzf-lua.

**Comment by ibhagwan** [comment]
Take a look at #441 for all the filtering possibilities for symbols, if this still doesn’t answer all your needs we can think of something.

**Comment by ajitid** [comment]
Is `regex_filter` attribute actually regex or is it [Lua pattern matching](https://riptutorial.com/lua/example/20315/lua-pattern-matching)?

**Comment by ibhagwan** [comment]
> Is regex_filter attribute actually regex or is it [Lua pattern matching](https://riptutorial.com/lua/example/20315/lua-pattern-matching)? I think excluding folders is a common use case, and I would rather prefer to have an ignore_patterns array [instead](https://github.com/ajitid/dotfiles/blob/d05933f26972d29310c7026e9e6ebd311663c5d1/nvim/.config/nvim/init.vim#L459-L467).

It’s a lua pattern, I can easily add `ignore_patterns` but the filtering is done on Fzf-lua’s side, the LSP query would still have to return the full result.

> My usecase is to exclude node_modules folder while doing a live workspace symbol search. Otherwise the plugin starts to crawl.

As I wrote above, I can add that but the filtering wouldn’t be at the LSP level so you’d still have to wait for the query to return unless you used `async = true` - have you tried it?

**Comment by ajitid** [comment]
Unsure if I'm doing something incorrectly, but I tried this:

```vim
:lua require'fzf-lua'.lsp_live_workspace_symbols({ async = true })
```

It didn't help much either. I'm still having lags while typing.

**Comment by ibhagwan** [comment]
> Unsure if I'm doing something incorrectly, but I tried this:
> 
> ```viml
> :lua require'fzf-lua'.lsp_live_workspace_symbols({ async = true })
> ```
> 
> It didn't help much either. I'm still having lags while typing.

That's because you're generating a new LSP query for each keystroke, I properly invested the time on optimizing this provider and it's on my TODO liss, is there any specific reason you prefer it over `lsp_workspace_symbols`?

Some LSP's, e.g. `gopls`, don't support getting symbols without specifying a query term and you have to use the `live_` variant, otherwise I'd recommend `lsp_workspace_symbols`.

**Comment by ajitid** [comment]
> is there any specific reason you prefer it over lsp_workspace_symbols?

I'm used to getting symbols while typing in VS Code and in Telescope so I have a preference for it.

**Comment by ibhagwan** [comment]
> > is there any specific reason you prefer it over lsp_workspace_symbols?
> 
> I'm used to getting symbols while typing in VS Code and in Telescope so I have a preference for it.

Alright, I guess that LSP refactor I was planning is overdue, keep an eye on this thread.

**Comment by ibhagwan** [comment]
I’m thinking of adding a `<C-g>` type of functionality to switch between workspace symbols and the live version, similar to what we already have with grep, that might boost your productivity here and also enable you to do more complex searches and exclusions.

**Comment by ajitid** [comment]
You're going to hate me for this — the reason for slowness was probably because I had the previewer open. With it disabled and the refactor you've made I find the search to be very responsive. So thank you for tackling this!

However, I still crave for a simple option to exclude paths while in `lsp_live_workspace_symbols` so that I do not have to first open lsp_live_workspace_symbols, then switch to fuzzy mode and then exclude unneeded paths like `!node_modules`. I think combining those four steps into 2 is a better experience.

**Comment by ibhagwan** [comment]
>You're going to hate me for this — the reason for slowness was probably because I had the previewer open. With it disabled and the refactor you've made I find the search to be very responsive. So thank you for tackling this!

No hate, this was on my TODO list anyways and it's a positive change in the LSP interface which brings it to feature parity with grep.

> However, I still crave for a simple option to exclude paths while in `lsp_live_workspace_symbols` so that I do not have to first open lsp_live_workspace_symbols, then switch to fuzzy mode and then exclude unneeded paths like `!node_modules`. I think combining those four steps into two will give a better experience.

Admittedly the "interactive" toggle solution is better suited for other types of searches, for excluding paths alone `ignore_patterns` is probably better, the reasons I didn't add it yet is because when I do it would make sense for this setting to work globally across all files providers which takes a bit more work, we can leave this issue open util I get around to it.

**Comment by ibhagwan** [comment]
@ajitid, make sure to update to https://github.com/ibhagwan/fzf-lua/commit/4707adc1ec9c5019590f6070ce578f68ed3a085c and see https://github.com/ibhagwan/fzf-lua/wiki#file-ignore-patterns how to use (exactly as in your Telescope settings).

Let me know if this works well / meets your needs and we can close this issue :-)

**Comment by ajitid** [comment]
Did this plugin used to clear out older search results before? Here's what I'm doing here:
1. Searched for `fuzzyMatchv1` using `:FzfLua lsp_live_workspace_symbols previewer=false`
2. Clear out search using ctrl+u. (Holding backspace would work similarly.)
3. Typed gibberish, and I found that it doesn't clears up search result even if it has found nothing against the current search query 

```sh
$ fzf --version  
0.30.0 (Fedora)
```

https://user-images.githubusercontent.com/26769888/178083286-588a9b74-f0b2-4710-85f2-58578372dd55.mp4

**Comment by ibhagwan** [comment]
> Did this plugin used to clear out older search results before? Here's what I'm doing here:
> 
> 1. Searched for `fuzzyMatchv1` using `:FzfLua lsp_live_workspace_symbols previewer=false`
> 2. Clear out search using ctrl+u. (Holding backspace would work similarly.)
> 3. Typed gibberish, and I found that it doesn't clears up search result even if it has found nothing against the current search query
> 
> ```shell
> $ fzf --version  
> 0.30.0 (Fedora)
> ```
> 
>  Kooha-07-09-2022-05-29-11.mp4

I’ll check why this happens, my guess is this is related to the default fzf denounce preventing the query from running too many times when typing fast, the question is why it doesn’t get cleared when you stop typing.


What happens if you type much slower?

**Comment by ajitid** [comment]
I think all what is happening is that if I search for "lang" and fzf shows few search results but typing x to make it "langx" returns none, then FZF rather clearing out its result list keeps showing the results of "langx".

Debounce is not the root cause I think, though typing slowers helps me to identify what the issue could be.

**Comment by ibhagwan** [comment]
> I think all what is happening is that if I search for "lang" and fzf shows few search results but typing x to make it "langx" returns none, then FZF rather clearing out its result list keeps showing the results of "langx".
> 
> Debounce is not the root cause I think, though typing slowers helps me to identify what the issue could be.

I can't seem to reproduce this, does this happen consistently or randomly? can you find some logic in how to activate this bug more acurately?

Also, I think I've experienced something similar in the past with `live_grep` but it disappeared once I upgraded to the latest version of `fzf`, what version of `fzf` are you on? It seems many bugs and improvements have been made in fzf's latest version when it comes to the `reload` action, if you're using an older version than `0.30` it's worth a shot upgrading.

**Comment by ajitid** [comment]
> I can't seem to reproduce this, does this happen consistently or randomly?

Consistently.

> can you find some logic in how to activate this bug more acurately?

Sure. I've tried with both typescript and a golang project. If you're using typescript, exclude "node_modules" and if go, then "go/src/". Open a project, then a typescript/go file to invoke LSP. After a few secs. run `:FzfLua lsp_live_workspace_symbols previewer=false` and type the name of a symbol that you already know exist. After that type some garbled characters after it (eg. start with `main` and then make it `mainqdfjsflsjlfdasf`). You would expect that `main` entry  to go away  because the query doesn't match anymore. But the result would persist.

> if you're using an older version than 0.30

I think I already mentioned that I'm on v0.30.

**Comment by ibhagwan** [comment]
Thanks for the reproduction steps @ajitid, I’ll try with `gopls`, hopefully I can reproduce this.

In case I’m still having issue reproducing can you run `:FzfLua lsp_live_workspace_symbols debug=true`?

It should output the query (and other important data) as you type, it would be helpful if you can post a screenshot of the debug data with the typed query once you reproduced the bug, `debug=true` should look like this:

![043899CD-2AD4-4432-B8D3-D08E944BB174](https://user-images.githubusercontent.com/59988195/178124691-4c4540c7-d011-4180-b194-d2a75d120f20.jpeg)

**Comment by ibhagwan** [comment]
@ajitid, https://github.com/ibhagwan/fzf-lua/commit/8c0408529ad11a8c0e29b7bc8c467a57b02996b0 - should solve it.

Let me know if you have any other issues and if you tested [`file_ignore_patterns`](https://github.com/ibhagwan/fzf-lua/wiki#file-ignore-patterns)?

**Comment by ajitid** [comment]
`file-ignore-patterns` works for me as expected!


> https://github.com/ibhagwan/fzf-lua/commit/8c0408529ad11a8c0e29b7bc8c467a57b02996b0 - should solve it.

I tried, and it didn't seem to fix it. `debug = true` seems to clear out the results but without it, the plugin doesn't:

https://user-images.githubusercontent.com/26769888/178128331-09232f73-8295-4f1c-a68d-32c7c4340097.mp4

**Comment by ibhagwan** [comment]
@ajitid can you try:
- `FzfLua lsp_live_workspace_symbols async=true`
- `FzfLua lsp_live_workspace_symbols async=false`

And let me know which one works and which one doesn’t? The issue was only with `async=false` which the commit fixed, I want to make sure I’m focusing on the right code route (different functions use for async).

**Comment by ajitid** [comment]
`async=false` works for me while `async=true` doesn't.

**Comment by ibhagwan** [comment]
> `async=false` works for me while `async=true` doesn't.

Does `async=true debug=true` also works while `async=true debug=false` fails? I'm trying to understand if it has something to do with the lack of lines returned to fzf as this doesn't get reproduced on my end.

**Comment by ajitid** [comment]
> Does async=true debug=true also works while async=true debug=false fails?

This is exactly what happens.

**Comment by ibhagwan** [comment]
Can you try with the latest commit https://github.com/ibhagwan/fzf-lua/commit/d6691568b7e99ce8b56b657d532262871c854ad5?

I suspect this has something to do with attaching multiple LSP clients (or perhaps `null-s` which also counts as an LSP client).

**Comment by ajitid** [comment]
It is still behaving as before, no difference that I can see.

**Comment by ibhagwan** [comment]
Don't bother testing, I just installed `null-ls`, it changes the number of clients from 1 to 2 which then causes the async version to wait endlessly for the 2nd client to return which never happens.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/4ac0092a4cc7dcd6da1572f9fd76ee564940fb52 - ok I think we got it now, I suspect you're using `null-ls` :-)

**Comment by ajitid** [comment]
Yep, you're right. And this fixes it, thanks!

**Comment by ibhagwan** [comment]
> Yep, you're right. And this fixes it, thanks!

Asynchronous bugs are always a bit tricky, thank you for your patience and diligence in helping me solve this :)
